/**
 * @file modules.h  (GENERATED by CMake from cmake/modules.h.in — do not edit)
 * @brief Build-time module switches. A module is ON iff its macro is defined.
 *
 * Controlled by -DMODULES=10110... (see CMakeLists.txt HARUKA_MODULE_LIST and
 * docs/guides/PLAN_MODULOS_BUILD.md). Guard module-specific code with
 *   #ifdef HARUKA_MOD_<NAME>
 * Both the engine and the game must be built with the same MODULES value.
 */
#pragma once

#define HARUKA_MOD_FLUIDS 1
#define HARUKA_MOD_DEFORM 1
#define HARUKA_MOD_SOFTBODY 1
#define HARUKA_MOD_NETWORK 1
#define HARUKA_MOD_AUDIO 1
#define HARUKA_MOD_PARTICLES 1
#define HARUKA_MOD_TERRAIN 1
#define HARUKA_MOD_POSTFX 1
#define HARUKA_MOD_SHADOWS 1
#define HARUKA_MOD_PHYSICS 1

